tunnel: 1635a8c1-0a08-4256-b6b3-7cccdfaea400
credentials-file: cloudflare/1635a8c1-0a08-4256-b6b3-7cccdfaea400.json
protocol: http2 # eduroam 対策

ingress:
  - hostname: gidaifes-slack-api.nutfes.net
    service: http://api:1323
  - hostname: gidaifes-slackbot.nutfes.net
    service: http://nutmeg-slackbot:3000
  - hostname: gidaifes-slack.nutfes.net
    service: http://vite-view:80
  - service: http_status:404
